language: java
env:
  secure: "BiZIDCtOy40/9O/h2RpIDoFEW/2AFDcGfnF0UzS446IgUcC2+J7fysw9s4Qqw5mEIFb9eANrEtOWz+hzZLdtRfl0W4JIc0O1UtOHQ67fUV8/quyymKCSWk4NyxA1IZ+KOcMOXQezVxZbkv/Bcu/9PLJaEvlB3x33VBCs95a5oq3L02CgB2rDj0slMlCqoH+kjfheQjE2B6S6qBTEnAwqteMTuYNkamQXtGuSC9UmtyY5gjyXFXF/GroxdaWuNHCKqtcYs3HovtnSWDjcUH5JVMtCwqQ0r3feUWqE6xk6HOioisrykauujDqBVHDPRw6ZSklFjGoE78tXWmTblgH0cgTEhEDxsFosMhQM0jIy6+qjPJFp4dQaUUCiqwNGWDy1ugmtwc7ml4Nb6zcdNUtEf2Erfo8sZPn0CPqscf9ViaXzLutu1/pXJaF30qe0KzeI+yvVVCa6BSxPhEcykMZYw+YMY2ewynIWMkUWis5zkYoRkpoAEfRvoZgROW6VybbDvrU/oFbdT60gSDHqpvu7zQqsrYJ2IGabkYTbgoI/AwwiII0YSmSBxN6ZfsGmTPiT1n9d02pddMsIDXsSYExhiE3ESABkCe+GdJWgx9s8Yby4kgZ3zpCkQaaag76EQlBNiZdTb1z2mX6CpXrKNXX7F+ODkGg1Ma9AfJtW3B9HaWQ="
jdk:
  - oraclejdk8
before_script:
  - chmod +x ./scripts/sonar-runner.sh
  - ./scripts/sonar-runner.sh
script:
  - ./scripts/build-index.sh
  - "/tmp/sonar-runner/sonar-runner-2.4/bin/sonar-runner -Dsonar.login=$SONAR_LOGIN -Dsonar.host.url=http://sonar.gadevs.ga/ -Dsonar.projectKey=ga.hellfish:hydroid -Dsonar.projectName=Hydroid -Dsonar.projectVersion=0.1 -Dsonar.sources=. -Dsonar.exclusions="
deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJ6KUCAF2VXKIRVNQ
    secret_access_key:
        secure: xiv5RSDBbbUT5f4arWvdS2H3UeKWJhRztg/FQFTVOrDOuuFk19fQvcMjhhzasqCeE6WvdhM3a/+q0tXuVOlWAD/AMyAN+BXnnxPY9YWRw7ynv8AHetFbPZn5NE4p2A8D5SAoyhE5ppceGs+NJ0he6lgPll/CZ0cZ/PJWA/m7mInvIwdAp2LyPFm9UnWtRtwNpnparOhMmS5z+eH8qZ1BEYKsfzEtruebk7GCThl8yMzPdoTQaSkHVDopO27MlXw/DhMbA8qaGGAfy2rt2Cw/eZnd8BkZOi7LGJ/sEHoVs7c7VoPHU9tzSWjjwUZHkn8DHRnQjifPMk8q8t1uTyJt4OGRQuh90DMzUZajmMqFWF7Lxj3SWqbITLu5KtDgxvkwc/AEiwOSFxE4pwBFoLH8TEGDIlkzckrKaIjsGmsjLKaFZd3+dx2tpj6FRISG5tDOTw7DwtO+6dTmfWRgKZNucUIfsloYxOH5M1iRyAdQtNm5row81E1SLBGgEeUO1+bsVeoH76fjZXAlpZiA8uzr0w3YVn+QLxMPIRaldYjDhjbbNOvWTpNbHsP1s/lsYmUGMCWzaI6TLugFDCvr2Da00pI86/C9msLJ649mWOD7FGw36vGyGKnW4YxaMhNGCwsCoxYM4kvJHl6Kumf2c9tTSRUr8l2xzEi3Du9NFTyzuxk=
    bucket: hydroid
    local_dir: staging
    upload_dir: vocabulary
    skip_cleanup: true
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAJ6KUCAF2VXKIRVNQ
    secret_access_key:
        secure: xiv5RSDBbbUT5f4arWvdS2H3UeKWJhRztg/FQFTVOrDOuuFk19fQvcMjhhzasqCeE6WvdhM3a/+q0tXuVOlWAD/AMyAN+BXnnxPY9YWRw7ynv8AHetFbPZn5NE4p2A8D5SAoyhE5ppceGs+NJ0he6lgPll/CZ0cZ/PJWA/m7mInvIwdAp2LyPFm9UnWtRtwNpnparOhMmS5z+eH8qZ1BEYKsfzEtruebk7GCThl8yMzPdoTQaSkHVDopO27MlXw/DhMbA8qaGGAfy2rt2Cw/eZnd8BkZOi7LGJ/sEHoVs7c7VoPHU9tzSWjjwUZHkn8DHRnQjifPMk8q8t1uTyJt4OGRQuh90DMzUZajmMqFWF7Lxj3SWqbITLu5KtDgxvkwc/AEiwOSFxE4pwBFoLH8TEGDIlkzckrKaIjsGmsjLKaFZd3+dx2tpj6FRISG5tDOTw7DwtO+6dTmfWRgKZNucUIfsloYxOH5M1iRyAdQtNm5row81E1SLBGgEeUO1+bsVeoH76fjZXAlpZiA8uzr0w3YVn+QLxMPIRaldYjDhjbbNOvWTpNbHsP1s/lsYmUGMCWzaI6TLugFDCvr2Da00pI86/C9msLJ649mWOD7FGw36vGyGKnW4YxaMhNGCwsCoxYM4kvJHl6Kumf2c9tTSRUr8l2xzEi3Du9NFTyzuxk=
    bucket: hydroid
    key: vocabulary/hydroid.zip
    bundle_type: zip
    application: hydroid-stanbol
    deployment_group: hydroid-stanbol
    region: ap-southeast-2
    on:
      branch: master
before_install:
  - openssl aes-256-cbc -k "$google_vision_key" -in google-vision.json.enc -out google-vision.json -d
  - chmod a+x ./scripts/build.sh
  - chmod a+x ./scripts/build-index.sh
install:
  - ./scripts/build.sh
