language: java
script: 
    - chmod a+x ./build.sh
    - ./build.sh
deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJ6KUCAF2VXKIRVNQ
    secret_access_key:
        secure: xiv5RSDBbbUT5f4arWvdS2H3UeKWJhRztg/FQFTVOrDOuuFk19fQvcMjhhzasqCeE6WvdhM3a/+q0tXuVOlWAD/AMyAN+BXnnxPY9YWRw7ynv8AHetFbPZn5NE4p2A8D5SAoyhE5ppceGs+NJ0he6lgPll/CZ0cZ/PJWA/m7mInvIwdAp2LyPFm9UnWtRtwNpnparOhMmS5z+eH8qZ1BEYKsfzEtruebk7GCThl8yMzPdoTQaSkHVDopO27MlXw/DhMbA8qaGGAfy2rt2Cw/eZnd8BkZOi7LGJ/sEHoVs7c7VoPHU9tzSWjjwUZHkn8DHRnQjifPMk8q8t1uTyJt4OGRQuh90DMzUZajmMqFWF7Lxj3SWqbITLu5KtDgxvkwc/AEiwOSFxE4pwBFoLH8TEGDIlkzckrKaIjsGmsjLKaFZd3+dx2tpj6FRISG5tDOTw7DwtO+6dTmfWRgKZNucUIfsloYxOH5M1iRyAdQtNm5row81E1SLBGgEeUO1+bsVeoH76fjZXAlpZiA8uzr0w3YVn+QLxMPIRaldYjDhjbbNOvWTpNbHsP1s/lsYmUGMCWzaI6TLugFDCvr2Da00pI86/C9msLJ649mWOD7FGw36vGyGKnW4YxaMhNGCwsCoxYM4kvJHl6Kumf2c9tTSRUr8l2xzEi3Du9NFTyzuxk=
    bucket: hydroid
    local_dir: indexing/dist
    upload_dir: vocabulary
    skip_cleanup: true
    on:
      branch: master
  - provider: codedeploy
    access_key_id: AKIAITTNVFBKCZRF7VTA
    secret_access_key:
        secure: xiv5RSDBbbUT5f4arWvdS2H3UeKWJhRztg/FQFTVOrDOuuFk19fQvcMjhhzasqCeE6WvdhM3a/+q0tXuVOlWAD/AMyAN+BXnnxPY9YWRw7ynv8AHetFbPZn5NE4p2A8D5SAoyhE5ppceGs+NJ0he6lgPll/CZ0cZ/PJWA/m7mInvIwdAp2LyPFm9UnWtRtwNpnparOhMmS5z+eH8qZ1BEYKsfzEtruebk7GCThl8yMzPdoTQaSkHVDopO27MlXw/DhMbA8qaGGAfy2rt2Cw/eZnd8BkZOi7LGJ/sEHoVs7c7VoPHU9tzSWjjwUZHkn8DHRnQjifPMk8q8t1uTyJt4OGRQuh90DMzUZajmMqFWF7Lxj3SWqbITLu5KtDgxvkwc/AEiwOSFxE4pwBFoLH8TEGDIlkzckrKaIjsGmsjLKaFZd3+dx2tpj6FRISG5tDOTw7DwtO+6dTmfWRgKZNucUIfsloYxOH5M1iRyAdQtNm5row81E1SLBGgEeUO1+bsVeoH76fjZXAlpZiA8uzr0w3YVn+QLxMPIRaldYjDhjbbNOvWTpNbHsP1s/lsYmUGMCWzaI6TLugFDCvr2Da00pI86/C9msLJ649mWOD7FGw36vGyGKnW4YxaMhNGCwsCoxYM4kvJHl6Kumf2c9tTSRUr8l2xzEi3Du9NFTyzuxk=
    bucket: hydroid
    key: vocabulary/hydroid.zip
    bundle_type: zip
    application: hydroid-stanbol
    deployment_group: hydroid-stanbol
    region: ap-southeast-2
    on:
      branch: master