language: java
script: 
    - chmod a+x ./build.sh
    - ./build.sh
deploy:
  - provider: s3
    region: ap-southeast-2
    access_key_id: AKIAJ6KUCAF2VXKIRVNQ
    secret_access_key:
        secure: R7+RYqlC4AlbfdaRQWtHg79BN9LXHPGIKVB47rQ+XjqIHUSJjV5YxmCFPMqpftKYRTx0dRzsk+1TWn8UTciDhBnyjA//MIsS2k9vTg+qX9MaNHAwa5JXmvMSFK9NNaFUaTnFMPjBe9sueu+eft3Xt8u6wIiCXhSBaL0vUFOzHBdX8ZtnALaJLokdr2rBFguQZhVg7oOsCI9L9uAK9BW3ky7BsWp9a1lV7E6DzZLOgqDArI1C/SAN60xHgggA5oiyiiLXnwfi7A0UCV3lWLSEEKVpsrFknvW5UgNbthEG7llxs+DhzgC5g9iuQwKvAUyegKm29Xk4lACDR0NWve5ojYy01mpwlsFSjO0vPD/6e//sHXOBICh15q9hCTMkgfWpVmEfHtv4/PYGOuaW1XDxM/c0ja2CKd54JrSQpe9luaEapUelD/PLMo005jdqYD0zqBbiMXzJRjSYNhF0bmETQUeHqKiHy6IigUawDhKeZ7hVqthMAy/1VsFrpbt3+oDk0gzZHeF4MwKKnJxlsEbnpt8exOfzuqEieV7TzEDDSzp9jofqyWtM66SgUP9dQieyOpGg98vuhZN4NE7GnwmL1hqy0Mw0aF9quEuj+FKGAwOPEIlXyMxFh6HsPJgeiBptfHK9nfQAcLSFbZLqUTY66IQB0u35eFJE=
    bucket: hydroid
    local_dir: indexing/dist
    upload_dir: vocabulary
    skip_cleanup: true
    on:
      branch: master