version: 0.0
os: linux
files:
  - source: /
    destination: /var/tmp/
permissions:
    - object: /var/tmp
      owner: root
      mode: 777
      type:
        - directory
hooks:
  AfterInstall:
    - location: reset_stanbol.sh
      timeout: 300
      runas: root
